language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

branches:
  only:
    - master
    - /^stable\d*$/

script:
  # Test lint
  - sh -c "ant test"


matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
